### ISSUE TITLE
Feature Roadmap

### ISSUE THREAD

**Issue by bfpimentel** [bfpimentel/counters-app#1]
# Feature Roadmap

### Repository
- [x] Create Feature Roadmap
- [x] Create Github Actions [feature/actions](https://github.com/bfpimentel/cornershop/tree/feature/actions)
- [x] Update README [feature/readme](https://github.com/bfpimentel/cornershop/tree/feature/readme)

### Server
- [x] Refactor to a offline-first approach [feature/server_refactoring](https://github.com/bfpimentel/cornershop/tree/feature/server_refactoring)

### App
- [x] Create Base Project Files [feature/base_project_files](https://github.com/bfpimentel/cornershop/tree/feature/base_project_files)
- [x] Structure Project Modules [feature/project_structuring](https://github.com/bfpimentel/cornershop/tree/feature/project_structuring)
- [x] Structure Project Dependencies [feature/project_dependencies](https://github.com/bfpimentel/cornershop/tree/feature/project_dependencies)
- [x] Set Styles and App Icon [feature/icons_and_styles](https://github.com/bfpimentel/cornershop/tree/feature/icons_and_styles)

### Welcome Screen
- [x] Fetch Counters when First Accessing the App [feature/first_counters_fetching](https://github.com/bfpimentel/cornershop/tree/feature/first_counters_fetching)

### Counters Screen
- [x] Get Counters [feature/counters_screen](https://github.com/bfpimentel/cornershop/tree/feature/counters_screen)
- [x] Counter Individual Add/Subtract [feature/individual_counter_add_and_subtract](https://github.com/bfpimentel/cornershop/tree/feature/individual_counter_add_and_subtract)
- [x] Search Counters [feature/search_counters](https://github.com/bfpimentel/cornershop/tree/feature/search_counters)
- [x] No Counters & No Results Layout [feature/layout_adjustments](https://github.com/bfpimentel/cornershop/tree/feature/layout_adjustments)

### Editing Counters
[feature/counters_editing_and_sharing](https://github.com/bfpimentel/cornershop/tree/feature/counters_editing_and_sharing)
- [x] Long Press to Start Editing
- [x] Delete Selected Counters
- [x] Share Selected Counters

### New Counter Screen
- [x] Create Counter Modal [feature/create_counter](https://github.com/bfpimentel/cornershop/tree/feature/create_counter)
- [x] Counter Examples Modal [feature/counters_examples](https://github.com/bfpimentel/cornershop/tree/feature/counters_examples)
